# Generated by Django 6.0 on 2025-12-13 21:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва матеріалу')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('unit', models.CharField(choices=[('шт', 'Штука'), ('кг', 'Кілограм'), ('т', 'Тонна'), ('м3', 'Метр кубічний'), ('м2', 'Метр квадратний'), ('м', 'Метр'), ('мп', 'Метр погонний'), ('л', 'Літр'), ('пак', 'Пакунок'), ('рул', 'Рулон')], max_length=10, verbose_name='Од. виміру')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Штрихкод / QR')),
                ('min_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Мін. ліміт')),
                ('current_avg_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Сер. собівартість')),
                ('market_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Поточна ринкова ціна')),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріали (Довідник)',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Вхід в систему'), ('CREATE', 'Створення'), ('UPDATE', 'Зміна'), ('DELETE', 'Видалення'), ('APPROVE', 'Погодження'), ('REJECT', 'Відхилення'), ('CHANGE_PRICE', 'Зміна ціни'), ('WRITEOFF', 'Списання'), ('TRANSFER', 'Переміщення')], max_length=20, verbose_name='Дія')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Було')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Стало')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.CharField(choices=[('draft', '📝 Чернетка'), ('new', '⏳ На погодженні'), ('rfq', '🔍 Тендер (RFQ)'), ('approved', '✅ Погоджено (PO)'), ('purchasing', '💸 У закупівлі'), ('in_transit', '🚚 У дорозі'), ('completed', '🏁 Виконано'), ('rejected', '🚫 Відхилено')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', '🟢 Не терміново'), ('normal', '🟡 Звичайно'), ('high', '🔴 Терміново!')], default='normal', max_length=10, verbose_name='Пріоритет')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата погодження')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='На коли треба?')),
                ('note', models.TextField(blank=True, verbose_name='Загальний коментар')),
                ('request_photo', models.ImageField(blank=True, null=True, upload_to='requests/', verbose_name='Фото до заявки')),
                ('audit_log', models.TextField(blank=True, default='', verbose_name='Історія змін')),
                ('supplier_info', models.CharField(blank=True, max_length=200, verbose_name='Постачальник (Текст)')),
                ('driver_name', models.CharField(blank=True, max_length=100, verbose_name='Водій ПІБ')),
                ('driver_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон водія')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, verbose_name='Номер авто')),
                ('shipping_doc', models.ImageField(blank=True, null=True, upload_to='shipping_docs/', verbose_name='Скан ТТН')),
                ('manager_last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='Хто погодив')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='warehouse.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Кількість (План)')),
                ('quantity_fact', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Кількість (Факт)')),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна закупівлі')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material', verbose_name='Матеріал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.order')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Компанія')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактна особа')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.IntegerField(default=5, verbose_name='Рейтинг (1-5)')),
                ('materials', models.ManyToManyField(blank=True, related_name='suppliers', to='warehouse.material', verbose_name='Постачає матеріали')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='selected_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.supplier', verbose_name='Постачальник'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото профілю')),
                ('position', models.CharField(blank=True, default='Співробітник', max_length=100, verbose_name='Посада')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Назва складу / Об'єкту")),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адреса')),
                ('is_main_storage', models.BooleanField(default=False, verbose_name='Це центральний склад?')),
                ('budget_limit', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Бюджет проекту')),
                ('assigned_users', models.ManyToManyField(blank=True, related_name='assigned_warehouses', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Прихід (Закупівля)'), ('OUT', 'Витрата (Робота)'), ('TRANSFER', 'Переміщення'), ('LOSS', '⚠️ Списання (Бій / Псування)')], max_length=10, verbose_name='Тип')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна (за од.)')),
                ('description', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запису')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата виконання')),
                ('work_type', models.CharField(blank=True, max_length=50, verbose_name='Вид робіт')),
                ('shift', models.CharField(default='1', max_length=10, verbose_name='Зміна')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='transactions/', verbose_name='Фото-звіт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Виконавець')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material', verbose_name='Матеріал')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.order', verbose_name='Заявка')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Транзакція',
                'verbose_name_plural': 'Журнал руху',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse', verbose_name='Звідки (Джерело)'),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_orders', to='warehouse.warehouse', verbose_name="Куди (Об'єкт)"),
        ),
        migrations.CreateModel(
            name='SupplierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Договірна ціна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='warehouse.material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='warehouse.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'material')},
            },
        ),
    ]
