# Generated by Django 6.0 on 2025-12-14 20:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_order_options_alter_transaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії матеріалів',
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Запис аудиту', 'verbose_name_plural': 'Журнал аудиту (Audit Log)'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='ordercomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='supplierprice',
            options={'verbose_name': 'Договірна ціна', 'verbose_name_plural': 'Прайс-лист постачальників'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакція', 'verbose_name_plural': 'Журнал руху'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': "Склад / Об'єкт", 'verbose_name_plural': 'Склади'},
        ),
        migrations.AddField(
            model_name='order',
            name='proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Фото факту'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ціна закупівлі'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Вхід в систему'), ('CREATE', 'Створення'), ('UPDATE', 'Зміна'), ('DELETE', 'Видалення'), ('APPROVE', 'Погодження'), ('REJECT', 'Відхилення'), ('CHANGE_PRICE', 'Зміна ціни'), ('WRITEOFF', 'Списання'), ('TRANSFER', 'Переміщення')], max_length=20, verbose_name='Дія'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_value',
            field=models.TextField(blank=True, null=True, verbose_name='Стало'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_value',
            field=models.TextField(blank=True, null=True, verbose_name='Було'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_avg_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Сер. собівартість'),
        ),
        migrations.AlterField(
            model_name='material',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Поточна ринкова ціна'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Мін. ліміт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата погодження'),
        ),
        migrations.AlterField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='Хто погодив'),
        ),
        migrations.AlterField(
            model_name='order',
            name='audit_log',
            field=models.TextField(blank=True, default='', verbose_name='Історія змін (Log)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Водій ПІБ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон водія'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='На коли треба?'),
        ),
        migrations.AlterField(
            model_name='order',
            name='manager_last_viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Менеджер бачив'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Причина / Коментар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', '🟢 Не терміново'), ('normal', '🟡 Звичайно'), ('high', '🔴 Терміново!')], default='normal', max_length=10, verbose_name='Пріоритет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='request_photo',
            field=models.ImageField(blank=True, null=True, upload_to='requests/', verbose_name='Фото до заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='selected_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.supplier', verbose_name='Обраний постачальник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_doc',
            field=models.ImageField(blank=True, null=True, upload_to='shipping_docs/', verbose_name='Скан ТТН (Відправка)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_orders', to='warehouse.warehouse', verbose_name='Звідки (Джерело)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', '📝 Чернетка'), ('new', '⏳ На погодженні'), ('rfq', '🔍 Тендер (RFQ)'), ('approved', '✅ Погоджено (PO)'), ('purchasing', '💸 У закупівлі'), ('in_transit', '🚚 У дорозі'), ('completed', '🏁 Виконано'), ('rejected', '🚫 Відхилено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Постачальник (Текст)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер авто'),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='text',
            field=models.TextField(verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Договірна ціна'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата запису'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Виконавець'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата виконання'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material', verbose_name='Матеріал'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.order', verbose_name="Пов'язана заявка"),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/', verbose_name='Фото-звіт'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ціна (за од.)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shift',
            field=models.CharField(choices=[('1', '1-ша зміна'), ('2', '2-га зміна'), ('3', 'Нічна')], default='1', max_length=10, verbose_name='Зміна'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Прихід (Закупівля)'), ('OUT', 'Витрата (Робота)'), ('TRANSFER', 'Переміщення'), ('LOSS', '⚠️ Списання (Бій / Псування)')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='work_type',
            field=models.CharField(blank=True, choices=[('foundation', 'Фундамент'), ('walls', 'Стіни / Кладка'), ('roof', 'Покрівля / Дах'), ('facade', 'Фасад'), ('interior', 'Внутрішнє оздоблення'), ('plumbing', 'Сантехніка'), ('electric', 'Електрика'), ('other', 'Інше')], max_length=50, verbose_name='Вид робіт'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Інші користувачі з доступом'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Бюджет проекту'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Матеріально відповідальний (МВО)'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.category', verbose_name='Категорія'),
        ),
    ]
