# Generated by Django 6.0 on 2026-01-01 15:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_category_alter_auditlog_options_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Матеріал', 'verbose_name_plural': 'Матеріали'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='ordercomment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Постачальник', 'verbose_name_plural': 'Постачальники'},
        ),
        migrations.AlterModelOptions(
            name='supplierprice',
            options={'verbose_name': 'Ціна постачальника', 'verbose_name_plural': 'Прайс-лист'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Рух матеріалів', 'verbose_name_plural': 'Журнал транзакцій'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': "Склад / Об'єкт", 'verbose_name_plural': "Склади та Об'єкти"},
        ),
        migrations.RemoveField(
            model_name='order',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='audit_log',
        ),
        migrations.RemoveField(
            model_name='order',
            name='manager_last_viewed_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier_price',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='assigned_users',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='is_main_storage',
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='construct_type',
            field=models.CharField(blank=True, choices=[('vertical', '↕️ Вертикаль (Колони/Стіни)'), ('horizontal', '↔️ Горизонталь (Плита/Перекриття)'), ('other', '🛠️ Інше')], default='other', max_length=20, verbose_name='Тип конструктиву'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='warehouses',
            field=models.ManyToManyField(blank=True, to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Створення'), ('UPDATE', 'Зміна'), ('DELETE', 'Видалення'), ('LOGIN', 'Вхід'), ('APPROVE', 'Погодження')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_avg_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Середня ціна'),
        ),
        migrations.AlterField(
            model_name='material',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ринкова ціна (довідково)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мін. залишок'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('шт', 'шт'), ('кг', 'кг'), ('т', 'тонн'), ('м', 'м'), ('м2', 'м²'), ('м3', 'м³'), ('л', 'л'), ('уп', 'уп'), ('год', 'год'), ('зм', 'зміна'), ('доба', 'доба')], default='шт', max_length=20, verbose_name='Од.вим.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Водій'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Бажана дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('normal', 'Звичайний'), ('high', 'Терміновий 🔥')], default='normal', max_length=20, verbose_name='Пріоритет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Фото факту прийому'),
        ),
        migrations.AlterField(
            model_name='order',
            name='request_photo',
            field=models.ImageField(blank=True, null=True, upload_to='requests/', verbose_name='Фото заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_doc',
            field=models.ImageField(blank=True, null=True, upload_to='shipping/', verbose_name='Фото накладної/ТТН'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='warehouse.warehouse', verbose_name='Звідки (для переміщень)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('rfq', 'Тендер (RFQ)'), ('approved', 'Погоджено'), ('purchasing', 'Закупівля'), ('in_transit', 'В дорозі'), ('completed', 'Виконано'), ('rejected', 'Відхилено'), ('draft', 'Чернетка')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier_info',
            field=models.CharField(blank=True, max_length=200, verbose_name='Інфо про постачальника (якщо немає в базі)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер авто'),
        ),
        migrations.AlterField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name="Об'єкт"),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_fact',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактично прийнято'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='supplier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна закупівлі'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна постачальника'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Хто провів'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата операції'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/', verbose_name='Фото-підтвердження'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна (за од.)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shift',
            field=models.CharField(choices=[('day', 'Денна'), ('night', 'Нічна')], default='day', max_length=20, verbose_name='Зміна'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', '🟢 Прихід'), ('OUT', '🔴 Витрата на роботи'), ('TRANSFER', '🔵 Переміщення'), ('LOSS', '⚠️ Списання (Бій/Втрата)')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='work_type',
            field=models.CharField(blank=True, choices=[('foundation', 'Фундамент'), ('walls', 'Стіни'), ('roof', 'Дах'), ('internal', 'Внутрішні роботи')], max_length=50, verbose_name='Вид робіт (Legacy)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бюджетний ліміт (грн)'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний (Прораб)'),
        ),
        migrations.CreateModel(
            name='ConstructionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва етапу')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name="Об'єкт")),
            ],
            options={
                'verbose_name': 'Етап будівництва',
                'verbose_name_plural': 'Етапи будівництва',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.constructionstage', verbose_name='Етап робіт'),
        ),
        migrations.CreateModel(
            name='StageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construct_type', models.CharField(choices=[('vertical', '↕️ Вертикаль (Колони/Стіни)'), ('horizontal', '↔️ Горизонталь (Плита/Перекриття)'), ('other', '🛠️ Інше')], default='other', max_length=20, verbose_name='Тип конструктиву')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Планова кількість')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material', verbose_name='Матеріал')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.constructionstage', verbose_name='Етап')),
            ],
            options={
                'verbose_name': 'Ліміт по етапу',
                'verbose_name_plural': 'Кошторис (Ліміти)',
            },
        ),
    ]
