# Generated by Django 6.0 on 2026-01-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_material_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='characteristics',
            field=models.CharField(blank=True, help_text='Наприклад: B25 P3 F200 W6 або Ø12 А500С', max_length=255, verbose_name='Характеристики (Марка/Клас)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Створення'), ('UPDATE', 'Зміна'), ('DELETE', 'Видалення'), ('LOGIN', 'Вхід'), ('APPROVE', 'Погодження'), ('REJECT', 'Відхилення')], max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('шт', 'шт'), ('kg', 'кг'), ('t', 'тонн'), ('m', 'м'), ('m2', 'м²'), ('m3', 'м³'), ('l', 'л'), ('pack', 'уп'), ('h', 'год'), ('shift', 'зміна'), ('day', 'доба')], default='шт', max_length=20, verbose_name='Од.вим.'),
        ),
    ]
