# Generated by Django 6.0 on 2026-01-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_material_characteristics_alter_auditlog_action_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='work_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID групи переміщення'),
        ),
    ]
