# Generated by Django 5.0.2 on 2024-03-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_remove_transaction_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='transfer_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID групи переміщення'),
        ),
    ]