# Generated by Django 6.0 on 2026-01-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_orderitem_transfer_group_id'),
        ('warehouse', '0008_add_transfer_group'),
    ]

    operations = [
    ]
