# Generated by Django 6.0 on 2026-01-04 19:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('warehouse', '0009_merge_20260104_2119'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionstage',
            options={'verbose_name': 'Етап будівництва', 'verbose_name_plural': 'Етапи будівництва'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Матеріал', 'verbose_name_plural': 'Довідник Матеріалів'},
        ),
        migrations.AlterModelOptions(
            name='stagelimit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplierprice',
            options={'verbose_name': 'Прайс постачальника'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакція', 'verbose_name_plural': 'Журнал транзакцій'},
        ),
        
        # --- FIX START: Safe removals (DROP IF EXISTS) ---
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_material DROP COLUMN IF EXISTS barcode CASCADE;",
            reverse_sql="ALTER TABLE warehouse_material ADD COLUMN barcode varchar(100);",
            state_operations=[migrations.RemoveField(model_name='material', name='barcode')]
        ),
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_order DROP COLUMN IF EXISTS approved_by_id CASCADE;",
            reverse_sql="ALTER TABLE warehouse_order ADD COLUMN approved_by_id integer;",
            state_operations=[migrations.RemoveField(model_name='order', name='approved_by')]
        ),
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_order DROP COLUMN IF EXISTS driver_name CASCADE;",
            reverse_sql="ALTER TABLE warehouse_order ADD COLUMN driver_name varchar(100);",
            state_operations=[migrations.RemoveField(model_name='order', name='driver_name')]
        ),
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_order DROP COLUMN IF EXISTS driver_phone CASCADE;",
            reverse_sql="ALTER TABLE warehouse_order ADD COLUMN driver_phone varchar(50);",
            state_operations=[migrations.RemoveField(model_name='order', name='driver_phone')]
        ),
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_order DROP COLUMN IF EXISTS selected_supplier_id CASCADE;",
            reverse_sql="ALTER TABLE warehouse_order ADD COLUMN selected_supplier_id bigint;",
            state_operations=[migrations.RemoveField(model_name='order', name='selected_supplier')]
        ),
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_order DROP COLUMN IF EXISTS supplier_info CASCADE;",
            reverse_sql="ALTER TABLE warehouse_order ADD COLUMN supplier_info varchar(200);",
            state_operations=[migrations.RemoveField(model_name='order', name='supplier_info')]
        ),
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_order DROP COLUMN IF EXISTS vehicle_number CASCADE;",
            reverse_sql="ALTER TABLE warehouse_order ADD COLUMN vehicle_number varchar(20);",
            state_operations=[migrations.RemoveField(model_name='order', name='vehicle_number')]
        ),
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_orderitem DROP COLUMN IF EXISTS transfer_group_id CASCADE;",
            reverse_sql="ALTER TABLE warehouse_orderitem ADD COLUMN transfer_group_id uuid;",
            state_operations=[migrations.RemoveField(model_name='orderitem', name='transfer_group_id')]
        ),
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_warehouse DROP COLUMN IF EXISTS responsible_id CASCADE;",
            reverse_sql="ALTER TABLE warehouse_warehouse ADD COLUMN responsible_id integer;",
            state_operations=[migrations.RemoveField(model_name='warehouse', name='responsible')]
        ),
        # --- FIX END: Safe removals ---

        # --- FIX START: Safe Adds (ADD COLUMN IF NOT EXISTS) ---
        
        # 1. ConstructionStage Dates
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_constructionstage ADD COLUMN IF NOT EXISTS end_date date;",
            reverse_sql="ALTER TABLE warehouse_constructionstage DROP COLUMN IF EXISTS end_date;",
            state_operations=[
                migrations.AddField(
                    model_name='constructionstage',
                    name='end_date',
                    field=models.DateField(blank=True, null=True),
                ),
            ]
        ),
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_constructionstage ADD COLUMN IF NOT EXISTS start_date date;",
            reverse_sql="ALTER TABLE warehouse_constructionstage DROP COLUMN IF EXISTS start_date;",
            state_operations=[
                migrations.AddField(
                    model_name='constructionstage',
                    name='start_date',
                    field=models.DateField(blank=True, null=True),
                ),
            ]
        ),

        # 2. Order Invoice File
        migrations.RunSQL(
            sql="ALTER TABLE warehouse_order ADD COLUMN IF NOT EXISTS invoice_file varchar(100);",
            reverse_sql="ALTER TABLE warehouse_order DROP COLUMN IF EXISTS invoice_file;",
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='invoice_file',
                    field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='Файл Рахунку'),
                ),
            ]
        ),

        # 3. Order Supplier FK
        migrations.RunSQL(
            sql=[
                "ALTER TABLE warehouse_order ADD COLUMN IF NOT EXISTS supplier_id bigint REFERENCES warehouse_supplier(id) DEFERRABLE INITIALLY DEFERRED;",
                "CREATE INDEX IF NOT EXISTS warehouse_order_supplier_id_idx ON warehouse_order(supplier_id);"
            ],
            reverse_sql="ALTER TABLE warehouse_order DROP COLUMN IF EXISTS supplier_id;",
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='supplier',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.supplier'),
                ),
            ]
        ),

        # 4. OrderItem Parent Item FK
        migrations.RunSQL(
            sql=[
                "ALTER TABLE warehouse_orderitem ADD COLUMN IF NOT EXISTS parent_item_id bigint REFERENCES warehouse_orderitem(id) DEFERRABLE INITIALLY DEFERRED;",
                "CREATE INDEX IF NOT EXISTS warehouse_orderitem_parent_item_id_idx ON warehouse_orderitem(parent_item_id);"
            ],
            reverse_sql="ALTER TABLE warehouse_orderitem DROP COLUMN IF EXISTS parent_item_id;",
            state_operations=[
                migrations.AddField(
                    model_name='orderitem',
                    name='parent_item',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.orderitem'),
                ),
            ]
        ),

        # 5. Warehouse Responsible User FK
        migrations.RunSQL(
            sql=[
                "ALTER TABLE warehouse_warehouse ADD COLUMN IF NOT EXISTS responsible_user_id bigint REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;",
                "CREATE INDEX IF NOT EXISTS warehouse_warehouse_responsible_user_id_idx ON warehouse_warehouse(responsible_user_id);"
            ],
            reverse_sql="ALTER TABLE warehouse_warehouse DROP COLUMN IF EXISTS responsible_user_id;",
            state_operations=[
                migrations.AddField(
                    model_name='warehouse',
                    name='responsible_user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Відповідальний'),
                ),
            ]
        ),
        # --- FIX END: Safe Adds ---

        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Створення'), ('UPDATE', 'Зміна'), ('DELETE', 'Видалення'), ('LOGIN', 'Вхід'), ('LOGOUT', 'Вихід'), ('ORDER_STATUS', 'Зміна статусу заявки'), ('ORDER_RECEIVED', 'Прийом товару')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='constructionstage',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Назва етапу'),
        ),
        migrations.AlterField(
            model_name='constructionstage',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='warehouse.warehouse', verbose_name="Об'єкт"),
        ),
        migrations.AlterField(
            model_name='material',
            name='article',
            field=models.CharField(max_length=50, unique=True, verbose_name='Артикул / Код'),
        ),
        migrations.AlterField(
            model_name='material',
            name='characteristics',
            field=models.CharField(blank=True, max_length=255, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='material',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ринкова ціна'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_limit',
            field=models.FloatField(default=0, verbose_name='Мін. залишок (сигнал)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва матеріалу'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('шт', 'штуки'), ('кг', 'кілограми'), ('т', 'тони'), ('м', 'метри'), ('м2', 'м.кв'), ('м3', 'м.куб'), ('л', 'літри'), ('компл', 'комплект'), ('год', 'години (послуги)')], default='шт', max_length=10, verbose_name='Од. виміру'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примітка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('medium', 'Звичайний'), ('high', 'Високий (Терміново)'), ('critical', 'Критичний (Зупинка)')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_orders', to='warehouse.warehouse', verbose_name='Зі складу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Чернетка'), ('new', 'Нова (На погодженні)'), ('rfq', 'Запит ціни (RFQ)'), ('approved', 'Погоджено (В закупівлі)'), ('purchasing', 'Замовлено (Оплачено)'), ('in_transit', 'В дорозі'), ('completed', 'Виконано (На складі)'), ('rejected', 'Відхилено')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouse.warehouse', verbose_name="На об'єкт"),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.FloatField(verbose_name='К-сть план'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_fact',
            field=models.FloatField(blank=True, null=True, verbose_name='К-сть факт'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ціна закупівлі'),
        ),
        migrations.AlterField(
            model_name='stagelimit',
            name='construct_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип конструкції (напр. Плита)'),
        ),
        migrations.AlterField(
            model_name='stagelimit',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.material'),
        ),
        migrations.AlterField(
            model_name='stagelimit',
            name='planned_quantity',
            field=models.FloatField(verbose_name='План (к-сть)'),
        ),
        migrations.AlterField(
            model_name='stagelimit',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='warehouse.constructionstage'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rating',
            field=models.IntegerField(default=5, verbose_name='Рейтинг (0-10)'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='construct_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Конструктив'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Створив'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='warehouse.material', verbose_name='Матеріал'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='warehouse.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/', verbose_name='Фото-факт'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ціна за од.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.constructionstage', verbose_name='Етап'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Прихід'), ('OUT', 'Витрата (Роботи)'), ('LOSS', 'Втрати/Бій'), ('TRANSFER', 'Переміщення (Legacy)')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='warehouse.warehouse', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='warehouses',
            field=models.ManyToManyField(blank=True, to='warehouse.warehouse', verbose_name='Доступні склади'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Назва складу / Об'єкту"),
        ),
        
        # --- FIX START: Safe AddIndex (CREATE INDEX IF NOT EXISTS) ---
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS warehouse_t_warehou_dbe75d_idx ON warehouse_transaction (warehouse_id, material_id);",
            reverse_sql="DROP INDEX IF EXISTS warehouse_t_warehou_dbe75d_idx;",
            state_operations=[
                migrations.AddIndex(
                    model_name='transaction',
                    index=models.Index(fields=['warehouse', 'material'], name='warehouse_t_warehou_dbe75d_idx'),
                ),
            ]
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS warehouse_t_date_905bae_idx ON warehouse_transaction (date);",
            reverse_sql="DROP INDEX IF EXISTS warehouse_t_date_905bae_idx;",
            state_operations=[
                migrations.AddIndex(
                    model_name='transaction',
                    index=models.Index(fields=['date'], name='warehouse_t_date_905bae_idx'),
                ),
            ]
        ),
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS warehouse_t_transfe_26d24e_idx ON warehouse_transaction (transfer_group_id);",
            reverse_sql="DROP INDEX IF EXISTS warehouse_t_transfe_26d24e_idx;",
            state_operations=[
                migrations.AddIndex(
                    model_name='transaction',
                    index=models.Index(fields=['transfer_group_id'], name='warehouse_t_transfe_26d24e_idx'),
                ),
            ]
        ),
        # --- FIX END: Safe AddIndex ---
    ]