# Generated by Django 6.0 on 2026-01-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_constructionstage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constructionstage',
            options={'ordering': ['id'], 'verbose_name': 'Етап будівництва', 'verbose_name_plural': 'Етапи будівництва'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='ordercomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='stagelimit',
            options={'verbose_name': 'Ліміт по етапу', 'verbose_name_plural': 'Кошторис (Ліміти)'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Транзакція', 'verbose_name_plural': 'Журнал транзакцій'},
        ),
        migrations.AddField(
            model_name='material',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='text',
            field=models.TextField(verbose_name='Повідомлення'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_prices', to='warehouse.material'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='warehouse.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
    ]
