# Generated by Django 6.0 on 2026-01-16 20:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_constructionstage_options_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='constructionstage',
            options={'verbose_name': 'Етап будівництва', 'verbose_name_plural': 'Етапи будівництва'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Матеріал', 'verbose_name_plural': 'Матеріали'},
        ),
        migrations.AlterModelOptions(
            name='stagelimit',
            options={'verbose_name': 'Ліміт матеріалу', 'verbose_name_plural': 'Ліміти матеріалів (Кошторис)'},
        ),
        migrations.AlterModelOptions(
            name='supplierprice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Транзакція', 'verbose_name_plural': 'Транзакції'},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='warehouse_t_transfe_26d24e_idx',
        ),
        migrations.RemoveField(
            model_name='material',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='material',
            name='market_price',
        ),
        migrations.RemoveField(
            model_name='material',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='invoice_file',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_doc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='parent_item',
        ),
        migrations.RemoveField(
            model_name='stagelimit',
            name='construct_type',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='materials',
        ),
        migrations.AddField(
            model_name='constructionstage',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.supplier', verbose_name='Постачальник'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Вхід в систему'), ('LOGOUT', 'Вихід'), ('CREATE', 'Створення'), ('UPDATE', 'Зміна'), ('DELETE', 'Видалення'), ('ORDER_STATUS', 'Зміна статусу заявки'), ('ORDER_RECEIVED', 'Прийом заявки')], max_length=20),
        ),
        migrations.AlterField(
            model_name='constructionstage',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець'),
        ),
        migrations.AlterField(
            model_name='constructionstage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Етап будівництва'),
        ),
        migrations.AlterField(
            model_name='constructionstage',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Початок'),
        ),
        migrations.AlterField(
            model_name='material',
            name='article',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Артикул / Код'),
        ),
        migrations.AlterField(
            model_name='material',
            name='characteristics',
            field=models.TextField(blank=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='material',
            name='current_avg_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Середня ціна'),
        ),
        migrations.AlterField(
            model_name='material',
            name='min_limit',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='Мін. залишок (ліміт)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(default='шт', max_length=20, verbose_name='Од. виміру'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='Очікувана дата'),
        ),
        migrations.AlterField(
            model_name='order',
            name='priority',
            field=models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('critical', 'Критичний 🔥')], default='medium', max_length=20, verbose_name='Пріоритет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='proof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='orders/proofs/', verbose_name='Фото ТТН/Факт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='request_photo',
            field=models.ImageField(blank=True, null=True, upload_to='orders/requests/', verbose_name='Фото заявки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_orders', to='warehouse.warehouse', verbose_name='Звідки (якщо переміщення)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('rfq', 'Запит ціни (RFQ)'), ('approved', 'Погоджено'), ('purchasing', 'У закупівлі'), ('transit', 'В дорозі'), ('completed', 'Виконано / На складі'), ('rejected', 'Відхилено')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse', verbose_name='Куди (Склад)'),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='text',
            field=models.TextField(verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='Кількість (План)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_fact',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='Кількість (Факт)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='supplier_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Ціна закупки'),
        ),
        migrations.AlterField(
            model_name='stagelimit',
            name='planned_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14, verbose_name='План. кількість'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва постачальника'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rating',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг надійності (0-100)'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Ціна (грн)'),
        ),
        migrations.AlterField(
            model_name='supplierprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата операції'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='warehouse.material'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='warehouse.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='transactions/', verbose_name='Фото підтвердження'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ціна (на момент)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.constructionstage', verbose_name='Етап робіт'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Прихід'), ('OUT', 'Списання'), ('LOSS', 'Втрати / Бій')], max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='budget_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Бюджетний ліміт (грн)'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='construct_type',
        ),
    ]
