# Generated by Django 5.2.13 on 2026-04-14 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чату Telegram для отримання сповіщень. Дізнайтесь у @userinfobot.', max_length=50, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='rating',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Рейтинг надійності (0-100)'),
        ),
        migrations.AlterUniqueTogether(
            name='stagelimit',
            unique_together={('stage', 'material')},
        ),
    ]
