# Generated by Django 5.2.13 on 2026-04-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_add_soft_delete_to_order_and_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changed_fields',
            field=models.JSONField(blank=True, help_text='JSON: {"field": {"old": "...", "new": "...", "label": "..."}}', null=True, verbose_name='Змінені поля'),
        ),
    ]
