# Generated by Django 5.2.13 on 2026-04-24 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_add_changed_fields_to_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.material', verbose_name='Матеріал'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='warehouse.material'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='warehouse.warehouse'),
        ),
        migrations.AddIndex(
            model_name='supplierprice',
            index=models.Index(fields=['supplier', 'material'], name='sp_supplier_material_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['responsible_user'], name='warehouse_responsible_user_idx'),
        ),
    ]
