"""
Django settings for construction_crm project.

Generated by 'django-admin startproject' using Django 5.0.
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Завантажуємо змінні з .env файлу
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- HELPER FUNCTIONS ---

def parse_bool(value, default=False):
    """Helper to parse boolean values from environment variables."""
    if value is None:
        return default
    # .strip() видаляє випадкові пробіли, які можуть бути в .env
    return str(value).strip().lower() in ('true', '1', 't', 'y', 'yes')

def parse_csv(value):
    """Helper to parse comma-separated strings into a list."""
    if not value:
        return []
    return [x.strip() for x in value.split(',') if x.strip()]


# --- ENVIRONMENT CONFIGURATION ---

# Визначаємо середовище: 'development' (default) або 'production'
DJANGO_ENV = os.getenv('DJANGO_ENV', 'development').strip()

# SAFEGUARD: Перевіряємо, яка команда запущена
IS_RUNSERVER = 'runserver' in sys.argv
IS_CHECK_OR_TEST = 'check' in sys.argv or 'test' in sys.argv

# --- SECURITY WARNING: keep the secret key used in production secret! ---
if DJANGO_ENV == 'production':
    SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
    # Fail-fast: якщо ключа немає на проді - падаємо одразу
    if not SECRET_KEY and not IS_CHECK_OR_TEST:
        raise ValueError("DJANGO_SECRET_KEY is required in production!")
else:
    # Fallback for dev only
    SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-key-change-me')

# --- SECURITY WARNING: don't run with debug turned on in production! ---
if DJANGO_ENV == 'production':
    # На проді DEBUG має бути False. 
    # Якщо забули виставити в .env, форсуємо False для безпеки.
    DEBUG = parse_bool(os.getenv('DJANGO_DEBUG', 'False'), False)
    
    # Критична перевірка: не дозволяємо запуск з DEBUG=True на проді
    if DEBUG and not IS_CHECK_OR_TEST:
        print("WARNING: Running in PRODUCTION mode with DEBUG=True is highly insecure!")
else:
    # У dev режимі DEBUG=True за замовчуванням
    DEBUG = parse_bool(os.getenv('DJANGO_DEBUG', 'True'), True)


# --- ALLOWED HOSTS ---
ALLOWED_HOSTS = parse_csv(os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost'))

# Фільтруємо wildcard '*' у production (небезпечно!)
if DJANGO_ENV == 'production':
    ALLOWED_HOSTS = [h for h in ALLOWED_HOSTS if h != '*']
    if not ALLOWED_HOSTS and not IS_CHECK_OR_TEST:
        raise ValueError("DJANGO_ALLOWED_HOSTS required in production (wildcard '*' not allowed)!")

# --- CSRF TRUSTED ORIGINS ---
# Для роботи за проксі (Nginx, Ngrok, etc.)
CSRF_TRUSTED_ORIGINS = parse_csv(os.getenv('CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1,http://localhost'))


# --- APP CONFIGURATION ---

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    # 'rest_framework', # Uncomment if needed
    
    # Local apps
    'warehouse',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Static files optimization
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'construction_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'construction_crm.wsgi.application'


# --- DATABASE ---

# Підключення PostgreSQL (credentials з .env)
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'warehouse_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Перевірка наявності пароля БД у production
if DJANGO_ENV == 'production' and not DATABASES['default']['PASSWORD'] and not IS_CHECK_OR_TEST:
    raise ValueError("DB_PASSWORD is required in production!")


# --- PASSWORD VALIDATION ---

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# --- INTERNATIONALIZATION ---

LANGUAGE_CODE = 'uk' # Українська локалізація

TIME_ZONE = 'Europe/Kiev' # Київський час

USE_I18N = True

USE_TZ = True


# --- STATIC & MEDIA ---

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Місце для глобальної статики (якщо треба)
STATICFILES_DIRS = [
    BASE_DIR / "static", # Переконайся, що папка існує
]

# Whitenoise compression (Django 4.2+ syntax)
# У тестах використовуємо простий storage без manifest
if IS_CHECK_OR_TEST:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }


# --- CACHING ---

# Локальний кеш для development, Redis для production (опційно)
CACHES = {
    'default': {
        'BACKEND': os.getenv(
            'CACHE_BACKEND',
            'django.core.cache.backends.locmem.LocMemCache'
        ),
        'LOCATION': os.getenv('CACHE_LOCATION', 'unique-snowflake'),
        'TIMEOUT': 300,  # 5 хвилин за замовчуванням
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}


# Налаштування для завантаження файлів (фото)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --- DEFAULT PRIMARY KEY ---

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- LOGIN / LOGOUT REDIRECTS ---

# Змінено на 'home' - нашу нову view-диспетчер
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGIN_URL = '/accounts/login/'


# --- EMAIL CONFIGURATION ---

# Email backend: 'console' для dev, 'smtp' для production
if DJANGO_ENV == 'production':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    try:
        EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    except ValueError:
        EMAIL_PORT = 587
    EMAIL_USE_TLS = parse_bool(os.getenv('EMAIL_USE_TLS', 'True'), True)
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@budsklad.com')
else:
    # В dev режимі листи виводяться в консоль
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@localhost'

# Адміністратори для сповіщень про 500 помилки
ADMINS = [
    (name.strip(), email.strip())
    for admin in parse_csv(os.getenv('DJANGO_ADMINS', ''))
    if ':' in admin
    for name, email in [admin.split(':', 1)]
]


# --- SECURITY HARDENING (PROD SPECIFIC) ---

if DJANGO_ENV == 'production':
    # HTTPS / SSL налаштування
    SECURE_SSL_REDIRECT = parse_bool(os.getenv('DJANGO_SECURE_SSL_REDIRECT', 'True'), True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Proxy configuration (e.g. Nginx, Heroku, AWS ELB)
    if parse_bool(os.getenv('DJANGO_BEHIND_PROXY', 'False')):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HSTS налаштування
    # Default 31536000 (1 рік) у prod. Env дозволяє налаштувати.
    try:
        SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    except ValueError:
        SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# --- LOGGING ---

LOG_LEVEL = os.getenv('DJANGO_LOG_LEVEL', 'INFO' if DJANGO_ENV == 'production' else 'DEBUG')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module}: {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'] if DJANGO_ENV == 'production' else ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['file', 'mail_admins'] if DJANGO_ENV == 'production' else ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'warehouse': {
            'handlers': ['console', 'file'] if DJANGO_ENV == 'production' else ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Створюємо директорію для логів, якщо не існує
(BASE_DIR / 'logs').mkdir(exist_ok=True)